// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ms'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​a​n​g​u​a​g​e
	 */
	lang: string
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​t​h​e​ ​{​n​a​m​e​}​ ​a​p​p​!
	 * @param {unknown} name
	 */
	greeting: RequiredParams<'name'>
	/**
	 * C​o​u​n​t​e​r​:​ ​{​c​o​u​n​t​}
	 * @param {unknown} count
	 */
	counter: RequiredParams<'count'>
	/**
	 * C​l​i​c​k​ ​m​e​!
	 */
	button: string
}

export type TranslationFunctions = {
	/**
	 * Language
	 */
	lang: () => LocalizedString
	/**
	 * Welcome to the {name} app!
	 */
	greeting: (arg: { name: unknown }) => LocalizedString
	/**
	 * Counter: {count}
	 */
	counter: (arg: { count: unknown }) => LocalizedString
	/**
	 * Click me!
	 */
	button: () => LocalizedString
}

export type Formatters = {}
