name: Production Deployment
on:
  workflow_dispatch:
    inputs:
      hash:
        type: string
        description: "Commit hash"
        required: true
      type:
        type: choice
        description: "Versioning type"
        required: true
        default: patch
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  deployments: write

env:
  PUBLIC_DEPLOY_ENV: production

jobs:
  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install

      - name: Build app (Web)
        run: npm run build -w apps/web

  release:
    name: Set Release
    runs-on: ubuntu-latest
    needs: deploy-production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.hash }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install

      - name: Set release version
        id: release
        uses: ./.github/actions/release
        with:
          type: ${{ github.event.inputs.type }}
