name: Staging Deployment

on:
  push:
    branches:
      - main

env:
  PUBLIC_DEPLOY_ENV: staging

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          cp ./apps/web/.env.example ./apps/web/.env
          cp ./apps/docs/.env.example ./apps/docs/.env

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test

      - name: Run linter
        run: npm run lint

      - name: Run type checker
        run: npm run check

      - name: Run formatter check
        run: npm run format:check
#
#  deploy-staging:
#    name: Deploy Staging
#    runs-on: ubuntu-latest
#    environment: Staging
#    needs: check
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Install Node.js
#        uses: actions/setup-node@v4
#        with:
#          cache: npm
#          node-version-file: ".nvmrc"
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: Build app (Web)
#        run: npm run build -w apps/web
